[versions]
hutool-v5 = '5.8.32'
hutool = '6.0.0-M17'
mapstruct = '1.6.2'
# fastjson = '2.0.53'
spring-boot = '3.3.5'
spring-cloud = '2023.0.3'
# spring-cloud-alibaba = '2023.0.1.2'
# spring-boot-admin = '3.3.4'

[libraries]
# bom libs
ihub-integration-bom = { module = 'pub.ihub.integration:ihub-bom', version = '0.1.8' }
ihub-module-bom = { module = 'pub.ihub.module:ihub-bom', version = '0.1.4' }
# hutool-v5-bom = { module = 'cn.hutool:hutool-bom', version.ref = 'hutool-v5' }
hutool-bom = { module = 'org.dromara.hutool:hutool-bom', version.ref = 'hutool' }
jmolecules-bom = { module = 'org.jmolecules:jmolecules-bom', version = '2023.1.7' }
mybatis-plus-bom = { module = 'com.baomidou:mybatis-plus-bom', version = '3.5.9' }
spring-modulith-bom = { module = 'org.springframework.modulith:spring-modulith-bom', version = '1.2.4' }
# spring-ai-bom = { module = 'org.springframework.ai:spring-ai-bom', version = '1.0.0-M1' }
spring-ai-bom = { module = 'io.github.pig-mesh.ai:spring-ai-bom', version = '1.3.0' }
spock-bom = { module = 'org.spockframework:spock-bom', version = '2.3-groovy-4.0' }
sa-token-bom = { module = 'cn.dev33:sa-token-bom', version = '1.39.0' }
okio-bom = { module = 'com.squareup.okio:okio-bom', version = '3.9.1' }
guava-bom = { module = 'com.google.guava:guava-bom', version = '33.3.1-jre' }
guice-bom = { module = 'com.google.inject:guice-bom', version = '7.0.0' }
axon-bom = { module = 'org.axonframework:axon-bom', version = '4.10.2' }
asm-bom = { module = 'org.ow2.asm:asm-bom', version = '9.7.1' }
# spring-boot-admin-dependencies = { module = 'de.codecentric:spring-boot-admin-dependencies', version.ref = 'spring-boot-admin' }
spring-cloud-dependencies = { module = 'org.springframework.cloud:spring-cloud-dependencies', version.ref = 'spring-cloud' }
# spring-cloud-alibaba-dependencies = { module = 'com.alibaba.cloud:spring-cloud-alibaba-dependencies', version.ref = 'spring-cloud-alibaba' }
spring-boot-dependencies = { module = 'org.springframework.boot:spring-boot-dependencies', version.ref = 'spring-boot' }
dante-cloud-dependencies = { module = 'cn.herodotus.engine:dependencies', version = '3.3.5.0' }
quarkus-dependencies = { module = 'io.quarkus:quarkus-bom', version = '3.16.0' }
# springdoc-openapi-dependencies = { module = 'org.springdoc:springdoc-openapi', version = '2.6.0' }

# log libs
commons-logging = { module = 'commons-logging:commons-logging' }
log4j = { module = 'log4j:log4j' }
slf4j-api = { module = 'org.slf4j:slf4j-api' }
log4j-core = { module = 'org.apache.logging.log4j:log4j-core' }
slf4j-jcl = { module = 'org.slf4j:slf4j-jcl' }
slf4j-log4j12 = { module = 'org.slf4j:slf4j-log4j12' }
jul-to-slf4j = { module = 'org.slf4j:jul-to-slf4j' }
log4j-over-slf4j = { module = 'org.slf4j:log4j-over-slf4j' }
jcl-over-slf4j = { module = 'org.slf4j:jcl-over-slf4j' }

# mapstruct libs
mapstruct = { module = 'org.mapstruct:mapstruct', version.ref = 'mapstruct' }
mapstruct-processor = { module = 'org.mapstruct:mapstruct-processor', version.ref = 'mapstruct' }

# doc libs
swagger-annotations = { module = 'io.swagger.core.v3:swagger-annotations' }

# groovy libs
groovy-core = { module = 'org.apache.groovy:groovy' }
groovy-datetime = { module = 'org.apache.groovy:groovy-datetime' }
groovy-dateutil = { module = 'org.apache.groovy:groovy-dateutil' }
groovy-groovydoc = { module = 'org.apache.groovy:groovy-groovydoc' }
groovy-json = { module = 'org.apache.groovy:groovy-json' }
groovy-nio = { module = 'org.apache.groovy:groovy-nio' }
groovy-sql = { module = 'org.apache.groovy:groovy-sql' }
groovy-templates = { module = 'org.apache.groovy:groovy-templates' }
groovy-xml = { module = 'org.apache.groovy:groovy-xml' }

# jmolecules libs
jmolecules-ddd = { module = 'org.jmolecules:jmolecules-ddd' }
jmolecules-events = { module = 'org.jmolecules:jmolecules-events' }
jmolecules-cqrs = { module = 'org.jmolecules:jmolecules-cqrs-architecture' }
jmolecules-layered = { module = 'org.jmolecules:jmolecules-layered-architecture' }
jmolecules-onion = { module = 'org.jmolecules:jmolecules-onion-architecture' }
jmolecules-spring = { module = 'org.jmolecules.integrations:jmolecules-spring' }
jmolecules-jpa = { module = 'org.jmolecules.integrations:jmolecules-jpa' }
jmolecules-jackson = { module = 'org.jmolecules.integrations:jmolecules-jackson' }
jmolecules-archunit = { module = 'org.jmolecules.integrations:jmolecules-archunit' }

# test libs
junit-jupiter = { module = 'org.junit.jupiter:junit-jupiter' }
spock-spring = { module = 'org.spockframework:spock-spring' }
spock-reports = { module = 'com.athaydes:spock-reports', version = '2.5.1-groovy-4.0' }
spring-boot-starter-test = { module = 'org.springframework.boot:spring-boot-starter-test' }
# verification libs
pmd = { module = 'com.alibaba.p3c:p3c-pmd', version = '2.1.1' }

# other libs
hutool-v5-all = { module = 'cn.hutool:hutool-all', version.ref = 'hutool-v5' }
# hutool-all = { module = 'org.dromara.hutool:hutool-all', version.ref = 'hutool' }
# fastjson = { module = 'com.alibaba.fastjson2:fastjson2', version.ref = 'fastjson' }
# fastjson-extension = { module = 'com.alibaba.fastjson2:fastjson2-extension', version.ref = 'fastjson' }
# fastjson-extension-spring = { module = 'com.alibaba.fastjson2:fastjson2-extension-spring6', version.ref = 'fastjson' }
# fastjson-kotlin = { module = 'com.alibaba.fastjson2:fastjson2-kotlin', version.ref = 'fastjson' }
# fastjson1 = { module = 'com.alibaba:fastjson', version.ref = 'fastjson' }
# justauth = { module = 'me.zhyd.oauth:JustAuth', version = '1.16.6' }

[bundles]
platform = [
    'ihub-integration-bom', 'ihub-module-bom', 'hutool-bom',
    'jmolecules-bom', 'spock-bom', 'sa-token-bom', 'okio-bom', 'asm-bom', 'guava-bom', 'guice-bom',
    'mybatis-plus-bom', 'spring-modulith-bom', 'spring-ai-bom', 'axon-bom',
    'spring-cloud-dependencies', 'spring-boot-dependencies', 'dante-cloud-dependencies'
]
constraints = [
    'hutool-v5-all', 'pmd', 'spock-reports', 'mapstruct', 'mapstruct-processor'
]
groovy = [
    'groovy-core', 'groovy-datetime', 'groovy-dateutil', 'groovy-groovydoc', 'groovy-json',
    'groovy-nio', 'groovy-sql', 'groovy-templates', 'groovy-xml'
]
slf4j-runtime = ['jul-to-slf4j', 'log4j-over-slf4j', 'jcl-over-slf4j']
jmolecules-cqrs = ['jmolecules-ddd', 'jmolecules-events', 'jmolecules-cqrs']
jmolecules-layered = ['jmolecules-ddd', 'jmolecules-events', 'jmolecules-layered']
jmolecules-onion = ['jmolecules-ddd', 'jmolecules-events', 'jmolecules-onion']
jmolecules-integrations = ['jmolecules-spring', 'jmolecules-jpa', 'jmolecules-jackson']
