[versions]
mapstruct = '1.6.3'
spring-boot = '3.4.0'
spring-cloud = '2023.0.4'
dante-cloud = '3.3.6.1'

[libraries]
# bom libs
ihub-integration-bom = { module = 'pub.ihub.integration:ihub-bom', version = '0.1.9' }
ihub-module-bom = { module = 'pub.ihub.module:ihub-bom', version = '0.2.0' }
#spring-ai-bom = { module = 'org.springframework.ai:spring-ai-bom', version = '1.0.0-M4' }
spring-ai-bom = { module = 'io.github.pig-mesh.ai:spring-ai-bom', version = '1.3.0' }
spock-bom = { module = 'org.spockframework:spock-bom', version = '2.3-groovy-4.0' }
sa-token-bom = { module = 'cn.dev33:sa-token-bom', version = '1.39.0' }
spring-cloud-dependencies = { module = 'org.springframework.cloud:spring-cloud-dependencies', version.ref = 'spring-cloud' }
spring-boot-dependencies = { module = 'org.springframework.boot:spring-boot-dependencies', version.ref = 'spring-boot' }
dante-cloud-dependencies = { module = 'cn.herodotus.engine:dependencies', version.ref = 'dante-cloud' }

# ddd libs
jmolecules-bom = { module = 'org.jmolecules:jmolecules-bom', version = '2023.2.1' }
spring-modulith-bom = { module = 'org.springframework.modulith:spring-modulith-bom', version = '1.3.0' }
axon-bom = { module = 'org.axonframework:axon-bom', version = '4.10.3' }
quarkus-dependencies = { module = 'io.quarkus:quarkus-bom', version = '3.17.2' }

# log libs
commons-logging = { module = 'commons-logging:commons-logging' }
log4j = { module = 'log4j:log4j' }
slf4j-api = { module = 'org.slf4j:slf4j-api' }
log4j-core = { module = 'org.apache.logging.log4j:log4j-core' }
slf4j-jcl = { module = 'org.slf4j:slf4j-jcl' }
slf4j-log4j12 = { module = 'org.slf4j:slf4j-log4j12' }
jul-to-slf4j = { module = 'org.slf4j:jul-to-slf4j' }
log4j-over-slf4j = { module = 'org.slf4j:log4j-over-slf4j' }
jcl-over-slf4j = { module = 'org.slf4j:jcl-over-slf4j' }

# mapstruct libs
mapstruct = { module = 'org.mapstruct:mapstruct', version.ref = 'mapstruct' }
mapstruct-processor = { module = 'org.mapstruct:mapstruct-processor', version.ref = 'mapstruct' }

# doc libs
swagger-annotations = { module = 'io.swagger.core.v3:swagger-annotations' }

# groovy libs
groovy-core = { module = 'org.apache.groovy:groovy' }
groovy-datetime = { module = 'org.apache.groovy:groovy-datetime' }
groovy-dateutil = { module = 'org.apache.groovy:groovy-dateutil' }
groovy-groovydoc = { module = 'org.apache.groovy:groovy-groovydoc' }
groovy-json = { module = 'org.apache.groovy:groovy-json' }
groovy-nio = { module = 'org.apache.groovy:groovy-nio' }
groovy-sql = { module = 'org.apache.groovy:groovy-sql' }
groovy-templates = { module = 'org.apache.groovy:groovy-templates' }
groovy-xml = { module = 'org.apache.groovy:groovy-xml' }

# jmolecules libs
jmolecules-ddd = { module = 'org.jmolecules:jmolecules-ddd' }
jmolecules-events = { module = 'org.jmolecules:jmolecules-events' }
jmolecules-cqrs = { module = 'org.jmolecules:jmolecules-cqrs-architecture' }
jmolecules-layered = { module = 'org.jmolecules:jmolecules-layered-architecture' }
jmolecules-onion = { module = 'org.jmolecules:jmolecules-onion-architecture' }
jmolecules-spring = { module = 'org.jmolecules.integrations:jmolecules-spring' }
jmolecules-jpa = { module = 'org.jmolecules.integrations:jmolecules-jpa' }
jmolecules-jackson = { module = 'org.jmolecules.integrations:jmolecules-jackson' }
jmolecules-archunit = { module = 'org.jmolecules.integrations:jmolecules-archunit' }

# test libs
junit-jupiter = { module = 'org.junit.jupiter:junit-jupiter' }
spock-spring = { module = 'org.spockframework:spock-spring' }
spock-reports = { module = 'com.athaydes:spock-reports', version = '2.5.1-groovy-4.0' }
spring-boot-starter-test = { module = 'org.springframework.boot:spring-boot-starter-test' }
# verification libs
pmd = { module = 'com.alibaba.p3c:p3c-pmd', version = '2.1.1' }

# webjars libs
webjars-layui = { module = 'org.webjars:layui', version = '2.9.18' }
webjars-jquery = { module = 'org.webjars:jquery', version = '3.7.1' }
webjars-crypto = { module = 'org.webjars.npm:crypto-js', version = '4.2.0' }

[bundles]
platform = [
    'ihub-integration-bom', 'ihub-module-bom',
    'jmolecules-bom', 'spock-bom', 'sa-token-bom', 'spring-modulith-bom', 'spring-ai-bom',
    'dante-cloud-dependencies'
]
constraints = [
    'pmd', 'spock-reports', 'mapstruct', 'mapstruct-processor'
]
groovy = [
    'groovy-core', 'groovy-datetime', 'groovy-dateutil', 'groovy-groovydoc', 'groovy-json',
    'groovy-nio', 'groovy-sql', 'groovy-templates', 'groovy-xml'
]
slf4j-runtime = ['jul-to-slf4j', 'log4j-over-slf4j', 'jcl-over-slf4j']
jmolecules-cqrs = ['jmolecules-ddd', 'jmolecules-events', 'jmolecules-cqrs']
jmolecules-layered = ['jmolecules-ddd', 'jmolecules-events', 'jmolecules-layered']
jmolecules-onion = ['jmolecules-ddd', 'jmolecules-events', 'jmolecules-onion']
jmolecules-integrations = ['jmolecules-spring', 'jmolecules-jpa', 'jmolecules-jackson']
