spring:
  security:
    oauth2:
      client:
        registration:
          ihub-oidc:
            provider: ihub
            client-id: ${spring.application.name}
            client-secret: ${ihub.secure.client.secret}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid
            client-name: ${spring.application.name}-oidc
          ihub-authorization-code:
            provider: ihub
            client-id: ${spring.application.name}
            client-secret: ${ihub.secure.client.secret}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/authorized"
            scope: ${ihub.secure.client.scope}
            client-name: ${spring.application.name}-authorization-code
          ihub-client-credentials:
            provider: ihub
            client-id: ${spring.application.name}
            client-secret: ${ihub.secure.client.secret}
            authorization-grant-type: client_credentials
            scope: ${ihub.secure.client.scope}
            client-name: ${spring.application.name}-client-credentials
          ihub-internal:
            provider: ihub
            client-id: ${spring.application.name}
            client-secret: ${ihub.secure.client.secret}
            authorization-grant-type: client_credentials
            scope: internal
            client-name: ${spring.application.name}-internal
        provider:
          ihub:
            issuer-uri: ${ihub.cloud.auth-server-addr}
