name: ESLint
on:
  schedule:
    - cron: '0 18 * * *'
#  push:
#    branches: main
#  pull_request:
#    branches: main

permissions:
  contents: read

jobs:
  ESLint:
    if: ${{ github.repository_owner == 'ihub-pub' }}
    permissions:
      contents: read
      security-events: write
      actions: read
    name: OSSAR Scan
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          disable-sudo: true
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Run OSSAR
        uses: github/ossar-action@786a16a90ba92b4ae6228fe7382fb16ef5c51000 # v1
        id: ossar

      - name: Upload OSSAR results
        uses: github/codeql-action/upload-sarif@db488ddef3bf6cb639b32c2e9a7c0a7ea8271d28 # v4.37.8
        with:
          sarif_file: ${{ steps.ossar.outputs.sarifFile }}
