name: ESLint
on:
  schedule:
    - cron: '0 18 * * *'
#  push:
#    branches: main
#  pull_request:
#    branches: main

permissions:
  contents: read

jobs:
  ESLint:
    if: ${{ github.repository_owner == 'ihub-pub' }}
    permissions:
      contents: read
      security-events: write
      actions: read
    name: OSSAR Scan
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          disable-sudo: true
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Run OSSAR
        uses: github/ossar-action@786a16a90ba92b4ae6228fe7382fb16ef5c51000 # v1
        id: ossar

      - name: Upload OSSAR results
        uses: github/codeql-action/upload-sarif@0d579ffd059c29b07949a3cce3983f0780820c98 # v4.32.6
        with:
          sarif_file: ${{ steps.ossar.outputs.sarifFile }}
