name: ESLint
on:
  schedule:
    - cron: '0 18 * * *'
#  push:
#    branches: main
#  pull_request:
#    branches: main

permissions:
  contents: read

jobs:
  ESLint:
    if: ${{ github.repository_owner == 'ihub-pub' }}
    permissions:
      contents: read
      security-events: write
      actions: read
    name: OSSAR Scan
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
        with:
          disable-sudo: true
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Run OSSAR
        uses: github/ossar-action@786a16a90ba92b4ae6228fe7382fb16ef5c51000 # v1
        id: ossar

      - name: Upload OSSAR results
        uses: github/codeql-action/upload-sarif@e46ed2cbd01164d986452f91f178727624ae40d7 # v4.35.3
        with:
          sarif_file: ${{ steps.ossar.outputs.sarifFile }}
